var _html_report_generator_service_8cs =
[
    [ "JiraRollupAgent.Services.HtmlReportGeneratorService.HtmlReportGeneratorService", "class_jira_rollup_agent_1_1_services_1_1_html_report_generator_service_1_1_html_report_generator_service.html", "class_jira_rollup_agent_1_1_services_1_1_html_report_generator_service_1_1_html_report_generator_service" ]
];