var _i_summarization_service_8cs =
[
    [ "JiraRollupAgent.Services.SummarizationService.ISummarizationService", "interface_jira_rollup_agent_1_1_services_1_1_summarization_service_1_1_i_summarization_service.html", "interface_jira_rollup_agent_1_1_services_1_1_summarization_service_1_1_i_summarization_service" ]
];