// <auto-generated />
using System;
using JiraRollupAgent.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JiraRollupAgent.DAL.Migrations
{
    [DbContext(typeof(JiraRollupDBContext))]
    [Migration("20260729014707_AddSummaryTables")]
    partial class AddSummaryTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JiraRollupAgent.DAL.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EpicId")
                        .HasColumnType("int");

                    b.Property<int?>("InitiativeId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int?>("WorkItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EpicId");

                    b.HasIndex("InitiativeId");

                    b.HasIndex("WorkItemId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("JiraRollupAgent.DAL.Models.Epic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InitiativeId")
                        .HasColumnType("int");

                    b.Property<string>("JiraId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InitiativeId");

                    b.ToTable("Epics");
                });

            modelBuilder.Entity("JiraRollupAgent.DAL.Models.EpicEngineeringSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EpicId")
                        .HasColumnType("int");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RangeEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RangeStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("SummaryText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EpicId")
                        .IsUnique();

                    b.ToTable("EpicEngineeringSummaries");
                });

            modelBuilder.Entity("JiraRollupAgent.DAL.Models.Initiative", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("JiraId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PriorityRank")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Initiatives");
                });

            modelBuilder.Entity("JiraRollupAgent.DAL.Models.InitiativeBusinessSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("InitiativeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RangeEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RangeStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("SummaryText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InitiativeId")
                        .IsUnique();

                    b.ToTable("InitiativeBusinessSummaries");
                });

            modelBuilder.Entity("JiraRollupAgent.DAL.Models.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("JiraRollupAgent.DAL.Models.WorkItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Assignee")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EpicId")
                        .HasColumnType("int");

                    b.Property<string>("JiraId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentWorkItemId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EpicId");

                    b.HasIndex("ParentWorkItemId");

                    b.ToTable("WorkItems");
                });

            modelBuilder.Entity("JiraRollupAgent.DAL.Models.WorkItemSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RangeEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RangeStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("SummaryText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkItemId")
                        .IsUnique();

                    b.ToTable("WorkItemSummaries");
                });

            modelBuilder.Entity("JiraRollupAgent.DAL.Models.Comment", b =>
                {
                    b.HasOne("JiraRollupAgent.DAL.Models.Epic", "Epic")
                        .WithMany("Comments")
                        .HasForeignKey("EpicId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("JiraRollupAgent.DAL.Models.Initiative", "Initiative")
                        .WithMany("Comments")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("JiraRollupAgent.DAL.Models.WorkItem", "WorkItem")
                        .WithMany("Comments")
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Epic");

                    b.Navigation("Initiative");

                    b.Navigation("WorkItem");
                });

            modelBuilder.Entity("JiraRollupAgent.DAL.Models.Epic", b =>
                {
                    b.HasOne("JiraRollupAgent.DAL.Models.Initiative", "Initiative")
                        .WithMany("Epics")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Initiative");
                });

            modelBuilder.Entity("JiraRollupAgent.DAL.Models.EpicEngineeringSummary", b =>
                {
                    b.HasOne("JiraRollupAgent.DAL.Models.Epic", "Epic")
                        .WithOne("EngineeringSummary")
                        .HasForeignKey("JiraRollupAgent.DAL.Models.EpicEngineeringSummary", "EpicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Epic");
                });

            modelBuilder.Entity("JiraRollupAgent.DAL.Models.InitiativeBusinessSummary", b =>
                {
                    b.HasOne("JiraRollupAgent.DAL.Models.Initiative", "Initiative")
                        .WithOne("BusinessSummary")
                        .HasForeignKey("JiraRollupAgent.DAL.Models.InitiativeBusinessSummary", "InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Initiative");
                });

            modelBuilder.Entity("JiraRollupAgent.DAL.Models.WorkItem", b =>
                {
                    b.HasOne("JiraRollupAgent.DAL.Models.Epic", "Epic")
                        .WithMany("WorkItems")
                        .HasForeignKey("EpicId");

                    b.HasOne("JiraRollupAgent.DAL.Models.WorkItem", "ParentWorkItem")
                        .WithMany("Children")
                        .HasForeignKey("ParentWorkItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Epic");

                    b.Navigation("ParentWorkItem");
                });

            modelBuilder.Entity("JiraRollupAgent.DAL.Models.WorkItemSummary", b =>
                {
                    b.HasOne("JiraRollupAgent.DAL.Models.WorkItem", "WorkItem")
                        .WithOne("Summary")
                        .HasForeignKey("JiraRollupAgent.DAL.Models.WorkItemSummary", "WorkItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkItem");
                });

            modelBuilder.Entity("JiraRollupAgent.DAL.Models.Epic", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("EngineeringSummary");

                    b.Navigation("WorkItems");
                });

            modelBuilder.Entity("JiraRollupAgent.DAL.Models.Initiative", b =>
                {
                    b.Navigation("BusinessSummary");

                    b.Navigation("Comments");

                    b.Navigation("Epics");
                });

            modelBuilder.Entity("JiraRollupAgent.DAL.Models.WorkItem", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Comments");

                    b.Navigation("Summary");
                });
#pragma warning restore 612, 618
        }
    }
}
