var searchData=
[
  ['a_20hard_20filter_0',['Role-weighting is soft (emphasis), not a hard filter',['../md__c_l_a_u_d_e.html#autotoc_md13',1,'']]],
  ['access_20layer_1',['&lt;span class=&quot;tt&quot;&gt;DAL/&lt;/span&gt; — data access layer',['../md__c_l_a_u_d_e.html#autotoc_md27',1,'']]],
  ['adapted_20from_20c_3a_20console_2',['App boilerplate (adapted from &lt;span class=&quot;tt&quot;&gt;C:\\UATP_CODE\\INSYTE\\StatusReporter\\StatusReporter.Console&lt;/span&gt;)',['../md__c_l_a_u_d_e.html#autotoc_md23',1,'']]],
  ['addasync_3',['AddAsync',['../class_jira_rollup_agent_1_1_d_a_l_1_1_repositories_1_1_implementations_1_1_repository-1-g.html#a9ac7684f96ae4e80c0b3d073b95dc756',1,'JiraRollupAgent.DAL.Repositories.Implementations.Repository-1-g.AddAsync()'],['../interface_jira_rollup_agent_1_1_d_a_l_1_1_repositories_1_1_interfaces_1_1_i_repository-1-g.html#a3072bc4e424c9125b6ce516f53eeb07d',1,'JiraRollupAgent.DAL.Repositories.Interfaces.IRepository-1-g.AddAsync()']]],
  ['addrangeasync_4',['AddRangeAsync',['../class_jira_rollup_agent_1_1_d_a_l_1_1_repositories_1_1_implementations_1_1_repository-1-g.html#a2dbf7c01e4f32f61941724b919378d45',1,'JiraRollupAgent.DAL.Repositories.Implementations.Repository-1-g.AddRangeAsync()'],['../interface_jira_rollup_agent_1_1_d_a_l_1_1_repositories_1_1_interfaces_1_1_i_repository-1-g.html#ada6e9d694b52fa48b25b7efcd65ab83e',1,'JiraRollupAgent.DAL.Repositories.Interfaces.IRepository-1-g.AddRangeAsync()']]],
  ['against_20vslivejirarollup_5',['against VSLiveJiraRollup',['../md__c_l_a_u_d_e.html#autotoc_md29',1,'Current data volume (verified against &lt;span class=&quot;tt&quot;&gt;VSLiveJiraRollup&lt;/span&gt;)'],['../md__c_l_a_u_d_e.html#autotoc_md28',1,'Table schema (verified against &lt;span class=&quot;tt&quot;&gt;VSLiveJiraRollup&lt;/span&gt;)']]],
  ['ai_20rocketeer_6',['vslhq26-ai-rocketeer',['../index.html',1,'']]],
  ['all_20three_20stages_7',['Load-once behavior (all three stages)',['../md__c_l_a_u_d_e.html#autotoc_md25',1,'']]],
  ['and_20their_20exact_20system_20prompts_20implemented_8',['The three prompt types, and their exact system prompts (implemented)',['../md__c_l_a_u_d_e.html#autotoc_md15',1,'']]],
  ['any_20implementation_9',['Known limits (from README, still applicable to any implementation)',['../md__c_l_a_u_d_e.html#autotoc_md30',1,'']]],
  ['app_20boilerplate_20adapted_20from_20c_3a_20console_10',['App boilerplate (adapted from &lt;span class=&quot;tt&quot;&gt;C:\\UATP_CODE\\INSYTE\\StatusReporter\\StatusReporter.Console&lt;/span&gt;)',['../md__c_l_a_u_d_e.html#autotoc_md23',1,'']]],
  ['appendcomments_11',['AppendComments',['../class_jira_rollup_agent_1_1_services_1_1_summarization_service_1_1_summarization_service.html#aaf6324566ac8f5fcfb2a4292972a187d',1,'JiraRollupAgent::Services::SummarizationService::SummarizationService']]],
  ['appendepic_12',['AppendEpic',['../class_jira_rollup_agent_1_1_services_1_1_html_report_generator_service_1_1_html_report_generator_service.html#a32484e630cd8dab774f7abaa6c87325b',1,'JiraRollupAgent::Services::HtmlReportGeneratorService::HtmlReportGeneratorService']]],
  ['appendinitiative_13',['AppendInitiative',['../class_jira_rollup_agent_1_1_services_1_1_html_report_generator_service_1_1_html_report_generator_service.html#a442c3092eddbcb6b990a768131662e8a',1,'JiraRollupAgent::Services::HtmlReportGeneratorService::HtmlReportGeneratorService']]],
  ['applicable_20to_20any_20implementation_14',['Known limits (from README, still applicable to any implementation)',['../md__c_l_a_u_d_e.html#autotoc_md30',1,'']]],
  ['applybold_15',['ApplyBold',['../class_jira_rollup_agent_1_1_services_1_1_html_report_generator_service_1_1_html_report_generator_service.html#a6b5973dd6b5b6099e534ca0187cbb858',1,'JiraRollupAgent::Services::HtmlReportGeneratorService::HtmlReportGeneratorService']]],
  ['architecture_16',['Architecture',['../index.html#autotoc_md2',1,'Architecture'],['../md__c_l_a_u_d_e.html#autotoc_md10',1,'Architecture']]],
  ['assignee_17',['Assignee',['../class_jira_rollup_agent_1_1_d_a_l_1_1_models_1_1_work_item.html#ad895aebc0890d260113bfd1073f26111',1,'JiraRollupAgent.DAL.Models.WorkItem.Assignee'],['../class_jira_rollup_agent_1_1_models_1_1_jira_hierarchy_loader_service_1_1_mock_work_item.html#adb549b8238587bf3cff3d323a959b939',1,'JiraRollupAgent.Models.JiraHierarchyLoaderService.MockWorkItem.Assignee'],['../class_jira_rollup_agent_1_1_models_1_1_jira_hierarchy_loader_service_1_1_mock_sub_item.html#ac7c36ce93828b1b969b258ec58783be0',1,'JiraRollupAgent.Models.JiraHierarchyLoaderService.MockSubItem.Assignee']]],
  ['author_18',['Author',['../class_jira_rollup_agent_1_1_d_a_l_1_1_models_1_1_comment.html#aa74ef89f9c2ab93285bf614cc9e2f037',1,'JiraRollupAgent.DAL.Models.Comment.Author'],['../class_jira_rollup_agent_1_1_models_1_1_jira_hierarchy_loader_service_1_1_mock_comment.html#a04ddd96e25c4089844b081b734df8cc4',1,'JiraRollupAgent.Models.JiraHierarchyLoaderService.MockComment.Author']]]
];
