var searchData=
[
  ['table_20schema_20verified_20against_20vslivejirarollup_0',['Table schema (verified against &lt;span class=&quot;tt&quot;&gt;VSLiveJiraRollup&lt;/span&gt;)',['../md__c_l_a_u_d_e.html#autotoc_md39',1,'']]],
  ['task_20pfd_201_204_20type_20a_20standalone_1',['Step 5 — Task TASK-PFD-1-4 (Type A, standalone)',['../md_prompt-types-overview.html#autotoc_md60',1,'']]],
  ['task_20task_20pfd_201_204_20type_20a_20standalone_2',['Step 5 — Task TASK-PFD-1-4 (Type A, standalone)',['../md_prompt-types-overview.html#autotoc_md60',1,'']]],
  ['team_20roster_20json_3',['&lt;span class=&quot;tt&quot;&gt;team-roster.json&lt;/span&gt;',['../md__c_l_a_u_d_e.html#autotoc_md33',1,'']]],
  ['tech_20stack_4',['Tech Stack',['../index.html#autotoc_md3',1,'']]],
  ['template_20two_20parameterizations_5',['Type C — Rollup summary, role-weighted (one template, two parameterizations)',['../md_prompt-types-overview.html#autotoc_md51',1,'']]],
  ['testing_6',['Testing',['../md__c_l_a_u_d_e.html#autotoc_md19',1,'']]],
  ['tests_7',['Running tests',['../index.html#autotoc_md10',1,'']]],
  ['the_20final_20report_20actually_20shows_8',['2. What the final report actually shows',['../md_prompt-types-overview.html#autotoc_md44',1,'']]],
  ['the_20full_20ticket_20hierarchy_9',['1. The full ticket hierarchy',['../md_prompt-types-overview.html#autotoc_md43',1,'']]],
  ['the_20primary_20pipeline_20input_10',['&lt;span class=&quot;tt&quot;&gt;jira-hierarchy.json&lt;/span&gt; (~5100 lines — the primary pipeline input)',['../md__c_l_a_u_d_e.html#autotoc_md31',1,'']]],
  ['the_20story_20not_20nested_20under_20it_11',['Step 4 — Bug BUG-PFD-1-3 (Type A, standalone — sibling of the Story, not nested under it)',['../md_prompt-types-overview.html#autotoc_md59',1,'']]],
  ['the_20three_20generic_20prompt_20types_12',['3. The three generic prompt types',['../md_prompt-types-overview.html#autotoc_md45',1,'']]],
  ['the_20three_20prompt_20types_20and_20their_20exact_20system_20prompts_20implemented_13',['The three prompt types, and their exact system prompts (implemented)',['../md__c_l_a_u_d_e.html#autotoc_md26',1,'']]],
  ['their_20exact_20system_20prompts_20implemented_14',['The three prompt types, and their exact system prompts (implemented)',['../md__c_l_a_u_d_e.html#autotoc_md26',1,'']]],
  ['this_20is_15',['What this is',['../md__c_l_a_u_d_e.html#autotoc_md17',1,'']]],
  ['three_20generic_20prompt_20types_16',['3. The three generic prompt types',['../md_prompt-types-overview.html#autotoc_md45',1,'']]],
  ['three_20prompt_20types_20and_20their_20exact_20system_20prompts_20implemented_17',['The three prompt types, and their exact system prompts (implemented)',['../md__c_l_a_u_d_e.html#autotoc_md26',1,'']]],
  ['three_20stages_18',['Load-once behavior (all three stages)',['../md__c_l_a_u_d_e.html#autotoc_md36',1,'']]],
  ['ticket_20hierarchy_19',['Ticket hierarchy',['../md__c_l_a_u_d_e.html#autotoc_md22',1,'']]],
  ['ticket_20hierarchy_20',['1. The full ticket hierarchy',['../md_prompt-types-overview.html#autotoc_md43',1,'']]],
  ['to_20any_20implementation_21',['Known limits (from README, still applicable to any implementation)',['../md__c_l_a_u_d_e.html#autotoc_md41',1,'']]],
  ['to_20end_20walkthrough_3a_20one_20initiative_20one_20example_20of_20each_20type_22',['5. End-to-end walkthrough: one Initiative, one example of each type',['../md_prompt-types-overview.html#autotoc_md55',1,'']]],
  ['together_23',['4. Tying it together',['../md_prompt-types-overview.html#autotoc_md54',1,'']]],
  ['two_20parameterizations_24',['Type C — Rollup summary, role-weighted (one template, two parameterizations)',['../md_prompt-types-overview.html#autotoc_md51',1,'']]],
  ['tying_20it_20together_25',['4. Tying it together',['../md_prompt-types-overview.html#autotoc_md54',1,'']]],
  ['type_26',['5. End-to-end walkthrough: one Initiative, one example of each type',['../md_prompt-types-overview.html#autotoc_md55',1,'']]],
  ['type_20a_27',['Type A',['../md_prompt-types-overview.html#autotoc_md56',1,'Step 1 — Subtask SUB-PFD-1-1-1 (Type A)'],['../md_prompt-types-overview.html#autotoc_md57',1,'Step 2 — StoryBug SBUG-PFD-1-1-1 (Type A)']]],
  ['type_20a_20—_20leaf_20summary_20no_20children_20no_20weighting_28',['Type A — Leaf summary (no children, no weighting)',['../md_prompt-types-overview.html#autotoc_md46',1,'']]],
  ['type_20a_20standalone_29',['Type A standalone',['../md_prompt-types-overview.html#autotoc_md60',1,'Step 5 — Task TASK-PFD-1-4 (Type A, standalone)'],['../md_prompt-types-overview.html#autotoc_md61',1,'Step 6 — Spike SPIKE-PFD-1-5 (Type A, standalone)']]],
  ['type_20a_20standalone_20—_20sibling_20of_20the_20story_20not_20nested_20under_20it_30',['Step 4 — Bug BUG-PFD-1-3 (Type A, standalone — sibling of the Story, not nested under it)',['../md_prompt-types-overview.html#autotoc_md59',1,'']]],
  ['type_20b_20—_20rollup_20summary_20no_20weighting_31',['Type B — Rollup summary, no weighting',['../md_prompt-types-overview.html#autotoc_md49',1,'']]],
  ['type_20b_20consumes_20steps_201_202_32',['Step 3 — Story STORY-PFD-1-1 (Type B, consumes Steps 1 &amp;amp; 2)',['../md_prompt-types-overview.html#autotoc_md58',1,'']]],
  ['type_20c_20—_20rollup_20summary_20role_20weighted_20one_20template_20two_20parameterizations_33',['Type C — Rollup summary, role-weighted (one template, two parameterizations)',['../md_prompt-types-overview.html#autotoc_md51',1,'']]],
  ['type_20c_20dev_20qa_20weighted_20consumes_20steps_203_206_34',['Step 7 — Epic EPIC-PFD-1 (Type C, Dev/QA-weighted, consumes Steps 3-6)',['../md_prompt-types-overview.html#autotoc_md62',1,'']]],
  ['type_20c_20scrummaster_20stakeholder_20em_20weighted_20consumes_20step_207_35',['Step 8 — Initiative INIT-PFD (Type C, ScrumMaster/Stakeholder/EM-weighted, consumes Step 7)',['../md_prompt-types-overview.html#autotoc_md63',1,'']]],
  ['type_20workflows_20json_36',['&lt;span class=&quot;tt&quot;&gt;issue-type-workflows.json&lt;/span&gt;',['../md__c_l_a_u_d_e.html#autotoc_md32',1,'']]],
  ['types_37',['Jira Rollup Agent — Hierarchy, Reporting Structure, and Prompt Types',['../md_prompt-types-overview.html',1,'']]],
  ['types_38',['3. The three generic prompt types',['../md_prompt-types-overview.html#autotoc_md45',1,'']]],
  ['types_20and_20their_20exact_20system_20prompts_20implemented_39',['The three prompt types, and their exact system prompts (implemented)',['../md__c_l_a_u_d_e.html#autotoc_md26',1,'']]]
];
