var searchData=
[
  ['table_20schema_20verified_20against_20vslivejirarollup_0',['Table schema (verified against &lt;span class=&quot;tt&quot;&gt;VSLiveJiraRollup&lt;/span&gt;)',['../md__c_l_a_u_d_e.html#autotoc_md28',1,'']]],
  ['task_20pfd_201_204_20type_20a_20standalone_1',['Step 5 — Task TASK-PFD-1-4 (Type A, standalone)',['../md_prompt-types-overview.html#autotoc_md49',1,'']]],
  ['task_20task_20pfd_201_204_20type_20a_20standalone_2',['Step 5 — Task TASK-PFD-1-4 (Type A, standalone)',['../md_prompt-types-overview.html#autotoc_md49',1,'']]],
  ['team_20roster_20json_3',['&lt;span class=&quot;tt&quot;&gt;team-roster.json&lt;/span&gt;',['../md__c_l_a_u_d_e.html#autotoc_md22',1,'']]],
  ['tech_20stack_4',['Tech Stack',['../index.html#autotoc_md3',1,'']]],
  ['template_20two_20parameterizations_5',['Type C — Rollup summary, role-weighted (one template, two parameterizations)',['../md_prompt-types-overview.html#autotoc_md40',1,'']]],
  ['the_20final_20report_20actually_20shows_6',['2. What the final report actually shows',['../md_prompt-types-overview.html#autotoc_md33',1,'']]],
  ['the_20full_20ticket_20hierarchy_7',['1. The full ticket hierarchy',['../md_prompt-types-overview.html#autotoc_md32',1,'']]],
  ['the_20primary_20pipeline_20input_8',['&lt;span class=&quot;tt&quot;&gt;jira-hierarchy.json&lt;/span&gt; (~5100 lines — the primary pipeline input)',['../md__c_l_a_u_d_e.html#autotoc_md20',1,'']]],
  ['the_20story_20not_20nested_20under_20it_9',['Step 4 — Bug BUG-PFD-1-3 (Type A, standalone — sibling of the Story, not nested under it)',['../md_prompt-types-overview.html#autotoc_md48',1,'']]],
  ['the_20three_20generic_20prompt_20types_10',['3. The three generic prompt types',['../md_prompt-types-overview.html#autotoc_md34',1,'']]],
  ['the_20three_20prompt_20types_20and_20their_20exact_20system_20prompts_20implemented_11',['The three prompt types, and their exact system prompts (implemented)',['../md__c_l_a_u_d_e.html#autotoc_md15',1,'']]],
  ['their_20exact_20system_20prompts_20implemented_12',['The three prompt types, and their exact system prompts (implemented)',['../md__c_l_a_u_d_e.html#autotoc_md15',1,'']]],
  ['this_20is_13',['What this is',['../md__c_l_a_u_d_e.html#autotoc_md8',1,'']]],
  ['three_20generic_20prompt_20types_14',['3. The three generic prompt types',['../md_prompt-types-overview.html#autotoc_md34',1,'']]],
  ['three_20prompt_20types_20and_20their_20exact_20system_20prompts_20implemented_15',['The three prompt types, and their exact system prompts (implemented)',['../md__c_l_a_u_d_e.html#autotoc_md15',1,'']]],
  ['three_20stages_16',['Load-once behavior (all three stages)',['../md__c_l_a_u_d_e.html#autotoc_md25',1,'']]],
  ['ticket_20hierarchy_17',['Ticket hierarchy',['../md__c_l_a_u_d_e.html#autotoc_md11',1,'']]],
  ['ticket_20hierarchy_18',['1. The full ticket hierarchy',['../md_prompt-types-overview.html#autotoc_md32',1,'']]],
  ['to_20any_20implementation_19',['Known limits (from README, still applicable to any implementation)',['../md__c_l_a_u_d_e.html#autotoc_md30',1,'']]],
  ['to_20end_20walkthrough_3a_20one_20initiative_20one_20example_20of_20each_20type_20',['5. End-to-end walkthrough: one Initiative, one example of each type',['../md_prompt-types-overview.html#autotoc_md44',1,'']]],
  ['together_21',['4. Tying it together',['../md_prompt-types-overview.html#autotoc_md43',1,'']]],
  ['two_20parameterizations_22',['Type C — Rollup summary, role-weighted (one template, two parameterizations)',['../md_prompt-types-overview.html#autotoc_md40',1,'']]],
  ['tying_20it_20together_23',['4. Tying it together',['../md_prompt-types-overview.html#autotoc_md43',1,'']]],
  ['type_24',['5. End-to-end walkthrough: one Initiative, one example of each type',['../md_prompt-types-overview.html#autotoc_md44',1,'']]],
  ['type_20a_25',['Type A',['../md_prompt-types-overview.html#autotoc_md45',1,'Step 1 — Subtask SUB-PFD-1-1-1 (Type A)'],['../md_prompt-types-overview.html#autotoc_md46',1,'Step 2 — StoryBug SBUG-PFD-1-1-1 (Type A)']]],
  ['type_20a_20—_20leaf_20summary_20no_20children_20no_20weighting_26',['Type A — Leaf summary (no children, no weighting)',['../md_prompt-types-overview.html#autotoc_md35',1,'']]],
  ['type_20a_20standalone_27',['Type A standalone',['../md_prompt-types-overview.html#autotoc_md49',1,'Step 5 — Task TASK-PFD-1-4 (Type A, standalone)'],['../md_prompt-types-overview.html#autotoc_md50',1,'Step 6 — Spike SPIKE-PFD-1-5 (Type A, standalone)']]],
  ['type_20a_20standalone_20—_20sibling_20of_20the_20story_20not_20nested_20under_20it_28',['Step 4 — Bug BUG-PFD-1-3 (Type A, standalone — sibling of the Story, not nested under it)',['../md_prompt-types-overview.html#autotoc_md48',1,'']]],
  ['type_20b_20—_20rollup_20summary_20no_20weighting_29',['Type B — Rollup summary, no weighting',['../md_prompt-types-overview.html#autotoc_md38',1,'']]],
  ['type_20b_20consumes_20steps_201_202_30',['Step 3 — Story STORY-PFD-1-1 (Type B, consumes Steps 1 &amp;amp; 2)',['../md_prompt-types-overview.html#autotoc_md47',1,'']]],
  ['type_20c_20—_20rollup_20summary_20role_20weighted_20one_20template_20two_20parameterizations_31',['Type C — Rollup summary, role-weighted (one template, two parameterizations)',['../md_prompt-types-overview.html#autotoc_md40',1,'']]],
  ['type_20c_20dev_20qa_20weighted_20consumes_20steps_203_206_32',['Step 7 — Epic EPIC-PFD-1 (Type C, Dev/QA-weighted, consumes Steps 3-6)',['../md_prompt-types-overview.html#autotoc_md51',1,'']]],
  ['type_20c_20scrummaster_20stakeholder_20em_20weighted_20consumes_20step_207_33',['Step 8 — Initiative INIT-PFD (Type C, ScrumMaster/Stakeholder/EM-weighted, consumes Step 7)',['../md_prompt-types-overview.html#autotoc_md52',1,'']]],
  ['type_20workflows_20json_34',['&lt;span class=&quot;tt&quot;&gt;issue-type-workflows.json&lt;/span&gt;',['../md__c_l_a_u_d_e.html#autotoc_md21',1,'']]],
  ['types_35',['Jira Rollup Agent — Hierarchy, Reporting Structure, and Prompt Types',['../md_prompt-types-overview.html',1,'']]],
  ['types_36',['3. The three generic prompt types',['../md_prompt-types-overview.html#autotoc_md34',1,'']]],
  ['types_20and_20their_20exact_20system_20prompts_20implemented_37',['The three prompt types, and their exact system prompts (implemented)',['../md__c_l_a_u_d_e.html#autotoc_md15',1,'']]]
];
